name 'zombodb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures zombodb'
long_description 'Installs/Configures zombodb'
version '0.1.0'

depends 'chef-sugar', '~> 3.1.0'
depends 'curl', '~> 2.0.1'
depends 'elasticsearch', '~1.0.0'
depends 'git'
depends 'java'
depends 'postgresql'
